"""
    cl2(x::Real)::Real

Returns the value of the Clausen function ``\\operatorname{Cl}_2(x)``
for a real angle ``x`` of type `Real`.  The Clausen function is
defined as

```math
\\operatorname{Cl}_2(x) = -\\int_0^x \\log|2\\sin(t/2)| dt
```

Author: Alexander Voigt

License: MIT

# Example
```jldoctest; setup = :(using ClausenFunctions), output = false
julia> cl2(1.0)
1.0139591323607684
```
"""
cl2(x::Real) = _cl2(float(x))

_cl2(x::Float16) = oftype(x, _cl2(Float32(x)))

_cl2(x::Float32) = oftype(x, _cl2(Float64(x)))

# Float64 Cl₂ on [0, π] uses two expansions:
#
#   0 ≤ a < π/3:   Cl₂(a) = a - a log(a) + a³ P₁(a²)
#   π/3 ≤ a ≤ π:   Cl₂(π - y) = y log(2) + y³ P₂(y²)
#
# P₁ and P₂ are minimax polynomials (relative error < 4e-18 w.r.t.
# Cl₂, generated by math/cl2_minimax.jl), so no division is needed.
# The split at π/3 keeps the more expensive branch with the logarithm
# short.  To keep the result within about one ulp, the reduced
# argument is carried as a double-word (hi, lo) pair, also for large
# |x| and near multiples of π.

# 1/e, log(2), π and π/2 as double-word constants (hi, lo)
const _CL2_INV_E = (3.6787944117144233e-01, -1.2428753672788363e-17)
const _CL2_E     =  2.718281828459045
const _CL2_LOG2  = (6.9314718055994531e-01,  2.3190468138462996e-17)
const _CL2_PI    = (3.1415926535897931e+00,  1.2246467991473532e-16)
const _CL2_PIO2  = (1.5707963267948966e+00,  6.1232339957367660e-17)
# 2π and 3π as triple-word and double-word constants
const _CL2_2PI   = (6.283185307179586, 2.4492935982947064e-16, -5.989539619436679e-33)
const _CL2_3PI   = (9.42477796076938, 3.6739403974420594e-16)
const _CL2_SPLIT = 1.0471975511965979 # π/3

# Cl₂(a) = a - a log(a) + a³ P₁(a²) for 0 ≤ a ≤ π/3
const _CL2_P1 = (0.0138888888888889, 6.944444444421995e-5,
                 7.873519794356167e-7, 1.1482210762374303e-8,
                 1.8979920143708932e-10, 3.3763677153696147e-12,
                 6.961725606139285e-14)

# Cl₂(π - y) = y log(2) + y³ P₂(y²) for |y| ≤ 2π/3
# P₂[1] = _CL2_P2[1] + _CL2_P2_LO
const _CL2_P2_LO = 4.625599467419612e-19
const _CL2_P2 = (-0.0416666666666669, -0.0010416666666599912,
                 -4.960317467046322e-5, -2.927964822195168e-6,
                 -1.941549014988993e-7, -1.386885927820381e-8,
                 -1.0470223099176043e-9, -7.865624315944863e-11,
                 -8.81749368332728e-12, 6.967552111864094e-13,
                 -5.619510045644151e-13, 1.5714897272684871e-13,
                 -3.749490329895447e-14, 6.144966727835925e-15,
                 -7.055564953857339e-16, 4.935411453326867e-17,
                 -1.6979415680364067e-18)

@inline function _cl2_horner(x::Float64, p::NTuple{N,Float64}) where N
    s = p[N]
    for i in N-1:-1:1
        s = muladd(s, x, p[i])
    end
    s
end

# evaluates p[1] + p[2] x + p[3] x² + ... as E(x²) + x O(x²), which
# halves the length of the dependency chain compared to Horner's scheme
@inline function _cl2_poly(x::Float64, p::NTuple{N,Float64}) where N
    x2 = x*x
    e = _cl2_horner(x2, ntuple(i -> p[2i - 1], (N + 1) ÷ 2))
    o = _cl2_horner(x2, ntuple(i -> p[2i], N ÷ 2))
    muladd(o, x, e)
end

# Cl₂(a + δ) for 0 < a ≤ π/3 and |δ| ≤ ulp(a)
@inline function _cl2_near0(a::Float64, δ::Float64 = 0.0)
    a < 0x1p-1000 && return a*(1 - log(a)) # a/e below may be subnormal
    # Cl₂(a) = a³ P₁(a²) - a log(a/e), where writing log(a) - 1 as
    # log(a/e) avoids cancellation for a ≈ e.
    t = a*a
    # a/e = zh + zl exactly (up to the error of 1/e)
    zh = a*_CL2_INV_E[1]
    zl = fma(a, _CL2_INV_E[1], -zh) + a*_CL2_INV_E[2]
    # a log(a/e) = a log(zh) + a zl/zh = a log(zh) + e zl
    L = log(zh)
    # δ Cl₁(a) with Cl₁(a) = -log(a) + a²/24 + O(a⁴) corrects for δ.
    # It is below one ulp of the result, so a rough log(a) from the
    # bit pattern of a (error < 0.06) suffices.
    loga = muladd(Float64(reinterpret(Int64, a)), 0x1p-52*_CL2_LOG2[1], -1023*_CL2_LOG2[1])
    # Sum the small terms first, so that the result is rounded only
    # once, when the dominant term -a log(zh) is added.
    w = fma(a*t, _cl2_poly(t, _CL2_P1), fma(δ, t/24 - loga, -_CL2_E*zl))
    fma(-a, L, w)
end

# Cl₂(π - y) for y = yh + yl, |y| ≤ π - _CL2_SPLIT, |yl| ≤ ulp(yh)
@inline function _cl2_nearpi(yh::Float64, yl::Float64)
    # Cl₂(π - y) = y h with h = log(2) + t p₀ + t² Q(t), t = y².
    # t p₀ is up to 30% of h, so h is computed as a double-word
    # (hh, hl) using error-free transformations; then y h is rounded
    # only once.
    t = yh*yh
    tl = fma(yh, yh, -t)              # t + tl = yh² exactly
    m = t*_CL2_P2[1]
    ml = fma(t, _CL2_P2[1], -m)       # m + ml = t p₀ exactly
    q = _cl2_poly(t, Base.tail(_CL2_P2))
    small = fma(t, fma(t, q, _CL2_P2_LO), fma(tl, _CL2_P2[1], ml))
    hh = _CL2_LOG2[1] + m             # Fast2Sum, |log(2)| > |m|
    hl = ((_CL2_LOG2[1] - hh) + m) + (small + _CL2_LOG2[2])
    # yl times the derivative d(y h)/dy = h + 2t (P₂(t) + t P₂'(t)),
    # where a few terms of P₂' suffice as yl is tiny
    p = fma(t, q, _CL2_P2[1])
    dp = fma(t, fma(t, 4*_CL2_P2[5], 3*_CL2_P2[4]), 2*_CL2_P2[3])
    dp = fma(t, dp, _CL2_P2[2])
    corr = yl*fma(2*t, fma(t, dp, p), hh)
    fma(yh, hh, fma(yh, hl, corr))
end

# Argument reduction: returns (k, s, h, l) such that
#   Cl₂(x) = sign(s) Cl₂(h + l)      if k (with 0 < h ≤ π/3)
#   Cl₂(x) = sign(s) Cl₂(π - h - l)  otherwise (with |h| ≤ 2π/3)
# where h + l is a double-word number with |l| ≤ ulp(h).  Requires
# π < |x| < ∞, with ax = |x|.
@inline function _cl2_reduce(x::Float64, ax::Float64)
    if ax <= _CL2_3PI[1]
        # For π < |x| ≤ 3π the differences |x| - kπ below are exact
        # (Sterbenz lemma), so no general argument reduction is needed.
        if ax <= _CL2_2PI[1] - _CL2_SPLIT
            # Cl₂(π + y) = -Cl₂(π - y) with y = |x| - π
            (false, -x, ax - _CL2_PI[1], -_CL2_PI[2])
        elseif ax <= _CL2_2PI[1] + _CL2_SPLIT
            # Cl₂(2π + y) = Cl₂(y) with y = |x| - 2π = yh + yl (Fast2Sum,
            # valid since |ax - 2π_hi| is 0 or ≥ ulp(4) > |2π_lo|)
            d = ax - _CL2_2PI[1]
            yh = d - _CL2_2PI[2]
            yl = ((d - yh) - _CL2_2PI[2]) - _CL2_2PI[3]
            (true, flipsign(yh, x), abs(yh), flipsign(yl, yh))
        else
            # Cl₂(3π - y) = Cl₂(π - y) with y = 3π - |x|
            (false, x, _CL2_3PI[1] - ax, _CL2_3PI[2])
        end
    else
        _cl2_reduce_large(x)
    end
end

# argument reduction for |x| > 3π, see _cl2_reduce
@noinline function _cl2_reduce_large(x::Float64)
    # x = n π/2 + (y₁ + y₂) with |y₁ + y₂| ≲ π/4, accurate also for
    # large |x| and near multiples of π.  For |x| < 2^14 this uses the
    # Cody–Waite reduction of Base.Math.rem_pio2_kernel (internal, but it
    # is what Base's rem2pi and sin/cos are built on; unlike rem2pi it
    # returns the remainder as a double-word).
    if abs(x) >= 0x1p14
        (q, y1, y2) = rem_pio2_large(x)
    else
        (n, y) = Base.Math.rem_pio2_kernel(x)
        (q, y1, y2) = (n & 3, y.hi, y.lo)
    end
    if q == 0     # Cl₂(y)
        (true, y1, abs(y1), flipsign(y2, y1))
    elseif q == 2 # Cl₂(π + y) = -Cl₂(π - y)
        (false, -1.0, y1, y2)
    else
        # q == 1: Cl₂(π/2 + y), q == 3: Cl₂(-π/2 + y) = -Cl₂(π/2 - y)
        s = q == 1 ? 1.0 : -1.0
        yh = flipsign(y1, s)
        yl = flipsign(y2, s)
        if yh < _CL2_SPLIT - _CL2_PIO2[1]
            # a = π/2 + y as double-word (Fast2Sum)
            ah = _CL2_PIO2[1] + yh
            al = ((_CL2_PIO2[1] - ah) + yh) + (_CL2_PIO2[2] + yl)
            (true, s, ah, al)
        else
            # π - a = π/2 - y as double-word (Fast2Sum)
            bh = _CL2_PIO2[1] - yh
            bl = ((_CL2_PIO2[1] - bh) - yh) + (_CL2_PIO2[2] - yl)
            (false, s, bh, bl)
        end
    end
end

# Cl₂(x) for |x| > π
@inline function _cl2_large(x::Float64, ax::Float64)
    isfinite(x) || return x - x # NaN for ±Inf and NaN
    (k, s, h, l) = _cl2_reduce(x, ax)
    flipsign(k ? _cl2_near0(h, l) : _cl2_nearpi(h, l), s)
end

# |x| ≤ π needs no argument reduction, so it is handled first
@inline function _cl2(x::Float64)::Float64
    ax = abs(x)
    if ax < _CL2_SPLIT
        iszero(ax) && return x
        copysign(_cl2_near0(ax), x)
    elseif ax <= _CL2_PI[1]
        # Float64(π) = π - 1.2e-16 is not a zero of Cl₂: the result is
        # ≈ 1.2e-16 log(2), cf. sin(Float64(π)) ≈ 1.2e-16
        copysign(_cl2_nearpi(_CL2_PI[1] - ax, _CL2_PI[2]), x)
    else
        _cl2_large(x, ax)
    end
end

# BigFloat Cl₂ via Kummer-accelerated Bernoulli series:
#
# Cl₂(θ)/θ = 3 - log[θ(1 - θ²/(4π²))] - (2π/θ)log((2π+θ)/(2π-θ))
#           + Σ_{n=1}^K (ζ(2n)-1)/(n(2n+1))  (θ/(2π))^{2n}
#
# valid for |θ| < 2π (always true after range reduction to [0, π]).
#
# Rewriting in the θ^{2n} basis avoids large intermediate values:
#
#   d_n = (ζ(2n)-1)/(n(2n+1)(2π)^{2n})
#       = |B_{2n}|/(2n(2n+1)(2n)!)  -  1/(n(2n+1)(2π)^{2n})
#
# The first term is exactly the standard Bernoulli coefficient (cheap,
# small values); the second is a trivial geometric correction.
#
# Compared to the unaccelerated series, ζ(2n)-1 ≈ 1/4^n roughly halves
# K at the worst case θ = π, while the coefficient computation stays
# as cheap as the original.
#
# Convergence rate: (θ/(4π))² per term (for large n).
# At θ = π (worst case): ~1.2 digits per term → K ≈ 0.83P for P digits.
# At θ = π/4: ~2.4 digits per term → K ≈ 0.42P.

# Cache: stores d_n for n = 1, ..., K.
const _cl2_coeff_cache = Ref{Vector{BigFloat}}(BigFloat[])
const _cl2_coeff_prec = Ref{Int}(0)
const _cl2_coeff_K = Ref{Int}(0)
const _cl2_coeff_lock = ReentrantLock()


function _cl2(x::BigFloat)
    (x, sgn) = range_reduce_even(x)

    iszero(x) && return x
    isnan(x) && return x
    x == BigFloat(pi) && return zero(x)

    # +10: guard digits to absorb rounding in the Horner loop and prefix.
    target_digits = ceil(Int, precision(BigFloat)*log10(2)) + 10

    twopi = 2*BigFloat(pi)
    v = x*x

    # Each series term decays by a factor of u = (θ/(2π))², giving
    # -2·log₁₀(θ/(2π)) decimal digits per term.  The Kummer acceleration
    # replaces ζ(2n) with ζ(2n)-1 ≈ 1/2^{2n} = 1/4ⁿ, contributing an
    # extra log₁₀(4) ≈ 0.602 digits per term (rounded down to 0.6).
    # The floor of 0.5 prevents division by zero for θ near 2π (which
    # cannot occur after range reduction to [0, π], but is defensive).
    ratio = Float64(x)/(2*Float64(pi))
    digits_per_term = max(-2*log10(ratio) + 0.6, 0.5)
    # +30: safety margin covering (a) the first ~10 terms where
    # ζ(2n)-1 ≫ 1/4ⁿ so convergence is slower than the asymptotic
    # estimate, and (b) any rounding in the Float64 K estimate.
    K = ceil(Int, target_digits/digits_per_term) + 30

    c = _cl2_ensure_coeffs(K)

    # Horner: S = v(d₁ + v(d₂ + ... + v dₖ))
    s = c[K]
    for k in (K - 1):-1:1
         s = muladd(s, v, c[k])
    end
    s *= v

    # Prefix: 3 - log[θ(1 - θ²/(4π²))] - (2π/θ)log((2π+θ)/(2π-θ))
    # log1p avoids cancellation for small θ where (2π+θ)/(2π-θ) ≈ 1.
    prefix = 3 - log(x*(one(x) - v/twopi^2)) - (twopi/x)*log1p(2*x/(twopi - x))

    sgn*x*(prefix + s)
end


# Compute Bernoulli numbers B_0, B_2, ..., B_{2K} via the standard recurrence.
function _bernoulli_even(K::Int)
    n = 2K
    B = zeros(BigFloat, n + 1)
    B[1] = one(BigFloat)
    B[2] = -one(BigFloat)/2

    for m in 2:n
        s = zero(BigFloat)
        binom = one(BigFloat)
        for k in 0:m-1
            s = binom*B[k + 1] + s
            binom = binom*(m + 1 - k)/(k + 1)
        end
        B[m + 1] = -s/(m + 1)
    end

    Beven = Vector{BigFloat}(undef, K + 1)

    for i in 0:K
        Beven[i + 1] = B[2i + 1]
    end

    Beven
end


# Compute and cache d_n = |B_{2n}|/(2n(2n+1)(2n)!) - 1/(n(2n+1)(2π)^{2n})
# for n = 1,...,K.
function _cl2_ensure_coeffs(K::Int)
    prec = precision(BigFloat)

    lock(_cl2_coeff_lock) do
        if _cl2_coeff_prec[] >= prec && _cl2_coeff_K[] >= K
            _cl2_coeff_cache[]
        else
            Beven = _bernoulli_even(K)

            inv_twopi_sq = 1/(2*BigFloat(pi))^2
            c = Vector{BigFloat}(undef, K)
            fac = one(BigFloat)
            inv_twopi_pow = one(BigFloat)

            for k in 1:K
                m = 2k
                fac *= (m - 1)*m # (2k)!
                inv_twopi_pow *= inv_twopi_sq # 1/(2π)^{2k}
                # Standard Bernoulli coefficient: |B_{2k}|/(2k(2k+1)(2k)!)
                orig = abs(Beven[k + 1])/(m*(m + 1)*fac)
                # Kummer correction: 1/(k(2k+1)(2π)^{2k})
                corr = inv_twopi_pow/(k*(m + 1))
                c[k] = orig - corr
            end

            _cl2_coeff_cache[] = c
            _cl2_coeff_prec[] = prec
            _cl2_coeff_K[] = K

            c
        end
    end
end
